namespace: data
cluster: polypia-cluster

deps: []

apps:
  # install name
  - name: redis-pull
    type: pull-helm
    specs:
      repo: bitnami
      chart: redis
#      chart_version: 17.13.2
#      app_version: 7.0.12
      dest: redis
  - name: redis
    type: install-helm
    specs:
      values:
        - redis.yaml

  - name: memcached-pull
    type: pull-helm
    specs:
      repo: bitnami
      chart: memcached
#      chart_version: 7.0.5
#      app_version: 1.6.27
      dest: memcached
  - name: memcached
    type: install-helm
    specs:
      values:
        - memcached.yaml

#    etcd:
#      repo: bitnami
##      chart_version: 9.2.0
##      app_version: 3.5.9
#      values:
#        - etcd.yaml
#    # https://github.com/openshift-helm-charts/charts/blob/main/README.md
#    # https://github.com/infinispan/infinispan-helm-charts
#    infinispan:
#      repo: openshift-helm-charts
##      chart_version: 0.3.2
##      app_version: 14.0
#      values:
#        - infinispan.yaml
